import { readFile, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { join } from 'node:path'
import { build, version } from 'esbuild'
import { parseArgs } from '../skills/repo-audit/scripts/lib/args.mjs'
import { resolveTarget } from '../skills/repo-audit/scripts/lib/repo.mjs'
import { createScratch } from '../skills/repo-audit/scripts/lib/scratch.mjs'
import { fileBytes } from '../skills/repo-audit/scripts/lib/protected-write.mjs'
import { hashBytes, canonicalJSON } from '../skills/repo-audit/scripts/lib/fingerprint.mjs'
import { resolveFilePath } from '../skills/repo-audit/scripts/lib/paths.mjs'
import { exactDiff } from '../skills/repo-audit/scripts/lib/proposed-edit.mjs'
import { CommandError, emitResult } from '../skills/repo-audit/scripts/lib/result.mjs'

// Generation always resolves authored sources from this checkout, never the target.
const root = fileURLToPath(new URL('../', import.meta.url))
// This is the canonical generated package resource.
const generatedPath = 'skills/repo-audit/scripts/bstack-check.mjs'

async function generate() {
  const result = await build({ absWorkingDir: root, entryPoints: ['scripts/checker-entry.mjs'], bundle: true,
    platform: 'node', target: 'node24', format: 'esm', write: false, metafile: true, legalComments: 'none' })
  const files = [...Object.keys(result.metafile.inputs), 'scripts/generate-checker.mjs', 'package.json', 'package-lock.json'].sort()
  const inputs = await Promise.all(files.map(async path => ({ path, sha256: hashBytes(await readFile(join(root, path))) })))
  const manifest = JSON.parse(await readFile(join(root, 'package.json'), 'utf8'))
  const buildVersion = { version: manifest.version, bundler: version, inputs: hashBytes(canonicalJSON(inputs)) }
  return '// Generated by scripts/generate-checker.mjs. Do not edit.\n' + result.outputFiles[0].text +
    '\n// Build identity binds validator sources, schemas and generation inputs.\nexport const buildVersion = ' + JSON.stringify(buildVersion) + '\n'
}

async function run(options) {
  const target = await resolveTarget(options)
  const content = await generate()
  const current = await fileBytes(join(root, generatedPath))
  if (options.check) return { status: current?.equals(Buffer.from(content)) ? 'passed' : 'failed',
    inputs: { repo: target.root }, problems: current?.equals(Buffer.from(content)) ? [] : [{ code: 'stale-checker',
      message: 'The generated checker is missing or stale.', fix: 'Regenerate in scratch and review the current bytes before replacing the generated resource.' }] }
  const path = '.bstack/bin/bstack-check.mjs'
  const original = await fileBytes(await resolveFilePath(target.root, path))
  const proposedHash = hashBytes(Buffer.from(content))
  const proposals = original?.equals(Buffer.from(content)) ? [] : [{ path,
    originalHash: original === null ? null : hashBytes(original), proposedHash,
    operation: original === null ? 'create' : 'replace-file', payload: { content }, proposedContent: content,
    diff: exactDiff(path, original === null ? null : original.toString('utf8'), content) }]
  const directory = await createScratch(target)
  await writeFile(join(directory, 'bstack-check.mjs'), content, { flag: 'wx' })
  const proposalsPath = join(directory, 'checker-proposals.json')
  await writeFile(proposalsPath, JSON.stringify({ proposals }, null, 2) + '\n', { flag: 'wx' })
  return { status: 'passed', inputs: { repo: target.root }, data: { path: proposalsPath,
    checkerPath: join(directory, 'bstack-check.mjs'), proposalsPath, proposedHash,
    next: 'Review the bytes, select the finding and bind the proposal to a change set. Install with apply --plan <file>.' } }
}

// Freshness uses in-memory generation; only explicit regeneration writes scratch.
const argv = process.argv.slice(2)
if (argv.length === 1 && argv[0] === '--help') {
  console.log('Usage: node scripts/generate-checker.mjs --repo <target> [--check] [--json]\nCheck canonical generated bytes without writes, or generate a checker and selected-plan install proposal in scratch. Aggregate execution is pending C24b.')
} else {
  try {
    const options = parseArgs(argv, ['check'])
    emitResult({ command: 'checker generate', ...await run(options) }, options.json)
  } catch (error) {
    emitResult({ command: 'checker generate', status: error instanceof CommandError ? error.status : 'blocked',
      problems: error instanceof CommandError ? error.problems : [{ code: 'generation-unavailable', message: error.message,
        fix: 'Restore checkout build dependencies and source files.' }] }, argv.includes('--json'))
  }
}
