import test from 'node:test'
import assert from 'node:assert/strict'
import { cp, mkdir, readFile, writeFile, symlink, rm } from 'node:fs/promises'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { spawnSync } from 'node:child_process'
import { maintenanceRepo } from './maintenance-fixture.mjs'
import { run, snapshot } from './discovery-fixture.mjs'
import { hashBytes, canonicalJSON } from '../../skills/repo-audit/scripts/lib/fingerprint.mjs'

const root = fileURLToPath(new URL('../../', import.meta.url))
const installedPath = '.bstack/bin/bstack-check.mjs'

async function setup(t, copySources = false) {
  const f = await maintenanceRepo(t)
  f.env = { ...process.env, XDG_CACHE_HOME: join(f.directory, 'cache'), LOCALAPPDATA: join(f.directory, 'cache'), HOME: f.directory, USERPROFILE: f.directory }
  f.source = root
  if (copySources) {
    f.source = join(f.directory, 'source')
    await mkdir(f.source)
    for (const path of ['scripts', 'skills/repo-audit/scripts', 'skills/repo-audit/schemas', 'package.json', 'package-lock.json']) {
      await cp(join(root, path), join(f.source, path), { recursive: true })
    }
    await symlink(join(root, 'node_modules'), join(f.source, 'node_modules'), 'junction')
  }
  return f
}

function generate(f, check = false) {
  const result = spawnSync(process.execPath, [join(f.source, 'scripts/generate-checker.mjs'), '--repo', f.repo, '--json', ...(check ? ['--check'] : [])],
    { encoding: 'utf8', cwd: f.directory, env: f.env, maxBuffer: Infinity })
  assert.equal(result.stderr, '')
  return { exit: result.status, ...JSON.parse(result.stdout) }
}

async function plan(f, proposal) {
  const findings = JSON.parse(await readFile(new URL('../inputs/findings-audit.json', import.meta.url), 'utf8'))
  findings.target.root = f.repo
  findings.reviewedScope = [installedPath]
  findings.findings[0].scope = [installedPath]
  findings.findings[0].files = [installedPath]
  await writeFile(join(f.directory, 'findings.json'), JSON.stringify(findings))
  const { diff, ...edit } = proposal
  const selected = { schemaVersion: 1, target: findings.target, findings: 'findings.json', findingsDigest: hashBytes(canonicalJSON(findings)),
    selectedFindingIds: ['F-001'], reviewedScope: [{ path: installedPath, resolvedPath: join(f.repo, installedPath) }],
    edits: [{ ...edit, id: 'checker', findingId: 'F-001' }] }
  const file = join(f.directory, 'plan.json')
  await writeFile(file, JSON.stringify({ ...selected, planDigest: hashBytes(canonicalJSON(selected)) }))
  return file
}

test('freshness passes without target or cache mutations', async t => {
  const f = await setup(t)
  const before = await snapshot(f.directory)
  assert.equal(generate(f, true).exit, 0)
  assert.deepEqual(await snapshot(f.directory), before)
})

for (const input of ['missing checker', 'generated bytes', 'validator', 'schema', 'build version', 'generation source']) {
  test(`freshness rejects stale ${input} without mutation`, async t => {
    const f = await setup(t, true)
    const paths = { 'missing checker': 'skills/repo-audit/scripts/bstack-check.mjs', 'generated bytes': 'skills/repo-audit/scripts/bstack-check.mjs', validator: 'skills/repo-audit/scripts/commands/docs-check.mjs',
      schema: 'skills/repo-audit/schemas/project.schema.json', 'build version': 'package.json', 'generation source': 'scripts/generate-checker.mjs' }
    const path = join(f.source, paths[input])
    const original = await readFile(path, 'utf8')
    if (input === 'missing checker') await rm(path)
    else await writeFile(path, input === 'schema' || input === 'build version' ?
      JSON.stringify({ ...JSON.parse(original), ...(input === 'schema' ? { title: 'Changed contract' } : { version: '1.2.3' }) }) : original + '\n// changed\n')
    const before = await snapshot(f.repo)
    const result = generate(f, true)
    assert.equal(result.exit, 1, JSON.stringify(result))
    assert.equal(result.problems[0].code, 'stale-checker')
    assert.deepEqual(await snapshot(f.repo), before)
  })
}

for (const existing of [false, true]) test(`scratch regeneration ${existing ? 'updates' : 'installs'} exact current bytes through selected apply`, async t => {
  const f = await setup(t)
  if (existing) {
    await mkdir(join(f.repo, '.bstack/bin'))
    await writeFile(join(f.repo, installedPath), 'previous checker\n')
  }
  const before = await snapshot(f.repo)
  const first = generate(f)
  const second = generate(f)
  assert.equal(first.exit, 0)
  assert.equal(second.exit, 0)
  const bytes = await readFile(first.data.checkerPath)
  assert.deepEqual(await readFile(second.data.checkerPath), bytes)
  assert.deepEqual(await snapshot(f.repo), before)
  const { proposals } = JSON.parse(await readFile(first.data.proposalsPath, 'utf8'))
  const file = await plan(f, proposals[0])
  assert.equal(run('apply', f.repo, f.env, ['--plan', file, '--dry-run']).exit, 0)
  assert.deepEqual(await snapshot(f.repo), before)
  assert.equal(run('apply', f.repo, f.env, ['--plan', file]).exit, 0)
  assert.deepEqual(await readFile(join(f.repo, installedPath)), bytes)
  const repeated = generate(f)
  assert.deepEqual(JSON.parse(await readFile(repeated.data.proposalsPath, 'utf8')).proposals, [])
})

for (const existing of [false, true]) test(`a changed ${existing ? 'existing' : 'new'} protected copy survives the reviewed install plan`, async t => {
  const f = await setup(t)
  await mkdir(join(f.repo, '.bstack/bin'))
  if (existing) await writeFile(join(f.repo, installedPath), 'previous checker\n')
  const generated = generate(f)
  const { proposals } = JSON.parse(await readFile(generated.data.proposalsPath, 'utf8'))
  const file = await plan(f, proposals[0])
  await writeFile(join(f.repo, installedPath), 'user checker\n')
  const before = await snapshot(f.repo)
  assert.equal(run('apply', f.repo, f.env, ['--plan', file]).exit, 1)
  assert.deepEqual(await snapshot(f.repo), before)
})

test('the standalone file uses embedded schemas and shared validators without a skill or dependencies', async t => {
  const f = await setup(t)
  const generated = generate(f)
  await cp(generated.data.checkerPath, join(f.directory, 'checker.mjs'))
  f.contract.generators = []
  await f.save()
  await writeFile(join(f.directory, 'assessment.json'), '{}')
  await writeFile(join(f.repo, 'README.md'), '# Source\n[broken](missing.md)\n')
  const before = await snapshot(f.repo)
  const source = `import { checkDocuments, validateContract, validateEvidence, checkGeneratedFacts, buildVersion } from './checker.mjs';
    const options = { repo: process.argv[1] };
    const contract = await validateContract(options);
    const docs = await checkDocuments(options);
    let evidence; try { await validateEvidence({ ...options, base: 'empty', assessment: './assessment.json' }) } catch (error) { evidence = error.problems[0].code }
    const generated = await checkGeneratedFacts(options);
    console.log(JSON.stringify({ contract, docs, evidence, generated, buildVersion }));`
  const result = spawnSync(process.execPath, ['--input-type=module', '-e', source, f.repo], { cwd: f.directory, env: f.env, encoding: 'utf8' })
  assert.equal(result.status, 0, result.stderr)
  const output = JSON.parse(result.stdout)
  assert.deepEqual(output.contract, { inputs: { repo: f.repo, contract: '.bstack/project.json' }, data: { contract: f.contract, coverageLimits: [] } })
  assert.deepEqual(output.docs, (() => { const { exit, schemaVersion, command, ...result } = run('docs check', f.repo, f.env); return result })())
  assert.equal(output.evidence, 'missing-field')
  assert.deepEqual(output.generated, { inputs: { repo: f.repo, contract: '.bstack/project.json' }, status: 'passed', data: { sections: [] }, problems: [] })
  assert.equal(output.buildVersion.version, JSON.parse(await readFile(join(root, 'package.json'), 'utf8')).version)
  assert.match(output.buildVersion.inputs, /^[0-9a-f]{64}$/)
  assert.deepEqual(await snapshot(f.repo), before)
})
